#!/usr/bin/env bash
# Shared, source-only helpers for the Azure ZeroTier lab scripts.

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '\033[36m[info]\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m[ ok ]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

require_commands() {
  local command_name missing=0
  for command_name in "$@"; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
      warn "Required command not found: ${command_name}"
      missing=1
    fi
  done
  [ "$missing" -eq 0 ] || die "Install the missing prerequisites and retry."
}

require_azure_login() {
  az account show --only-show-errors -o none 2>/dev/null ||
    die "Azure CLI is not logged in. Run 'az login' and retry."
}

az_vm_run() {
  local resource_group="$1" vm_name="$2" remote_script="$3" output attempt
  local marker="__AZURE_ZT_LAB_RUN_COMMAND_OK__"
  for attempt in 1 2 3 4; do
    if output="$(az vm run-command invoke \
      --resource-group "$resource_group" \
      --name "$vm_name" \
      --command-id RunShellScript \
      --scripts "set -eu
${remote_script}
printf '\n${marker}\n'" \
      --only-show-errors \
      --query 'value[].message' \
      --output tsv 2>&1)"; then
      output="${output//$'\r'/}"
      if printf '%s\n' "$output" | grep -qF "$marker"; then
       printf '%s\n' "$output" | sed "/${marker}/d"
       return 0
      fi
    else
      output="${output//$'\r'/}"
    fi

    printf '%s\n' "$output" >&2
    if printf '%s\n' "$output" |
      grep -Eq 'ResourceNotFound|ResourceGroupNotFound|AuthorizationFailed|InvalidSubscriptionId|SubscriptionNotFound'; then
      break
    fi
    if [ "$attempt" -lt 4 ]; then
      warn "Run Command was interrupted on ${vm_name}; retrying (${attempt}/4)."
      sleep $((attempt * 15))
    fi
  done

  warn "Run Command did not complete successfully on ${vm_name} after ${attempt} attempt(s)."
  return 1
}

az_vm_install_zerotier() {
  local resource_group="$1" vm_name="$2"
  az_vm_run "$resource_group" "$vm_name" \
    "sudo cloud-init status --wait
if ! command -v zerotier-cli >/dev/null 2>&1; then
  installer=/var/tmp/zt-lab-install-zerotier.sh
  curl -fsSL --connect-timeout 10 --max-time 120 --retry 3 \
    https://install.zerotier.com -o \"\$installer\"
  sudo systemd-run --unit=zt-lab-install-zerotier --collect \
    --property=Type=oneshot /bin/bash \"\$installer\"
fi"

  az_vm_run "$resource_group" "$vm_name" \
    "ready=0
for attempt in \$(seq 1 60); do
  if command -v zerotier-cli >/dev/null 2>&1 &&
    sudo systemctl is-active --quiet zerotier-one; then
    sudo zerotier-cli info
    ready=1
    break
  fi
  if sudo systemctl is-failed --quiet zt-lab-install-zerotier.service; then
    sudo journalctl -u zt-lab-install-zerotier --no-pager -n 50
    break
  fi
  sleep 5
done
if [ \"\$ready\" -ne 1 ]; then
  sudo journalctl -u zt-lab-install-zerotier --no-pager -n 50
  false
fi"
}

b64_file() {
  if base64 --help 2>&1 | grep -q -- '-w'; then
    base64 -w0 "$1"
  else
    base64 "$1" | tr -d '\n'
  fi
}

valid_ipv4() {
  local ip="$1" octet
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS=. read -r -a octets <<< "$ip"
  for octet in "${octets[@]}"; do
    [ "$octet" -le 255 ] || return 1
  done
}

valid_ipv4_source() {
  local source="$1" ip prefix
  ip="$source"
  if [[ "$source" == */* ]]; then
    ip="${source%/*}"
    prefix="${source#*/}"
    [[ "$prefix" =~ ^[0-9]+$ ]] && [ "$prefix" -le 32 ] || return 1
  fi
  valid_ipv4 "$ip"
}

valid_zt_network_id() {
  [[ "$1" =~ ^[0-9A-Fa-f]{16}$ ]]
}

resolve_public_ip() {
  local endpoint value
  for endpoint in https://api.ipify.org https://ifconfig.me/ip; do
    value="$(curl -fsS --connect-timeout 5 --max-time 15 --retry 2 "$endpoint" 2>/dev/null || true)"
    if valid_ipv4 "$value"; then
      printf '%s\n' "$value"
      return 0
    fi
  done
  return 1
}

read_ssh_public_key() {
  local path="$1" key
  [ -f "$path" ] || die "SSH public key file not found: ${path}"
  key="$(<"$path")"
  [[ "$key" =~ ^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521))[[:space:]] ]] ||
    die "SSH public key has an unsupported format: ${path}"
  printf '%s\n' "$key"
}

env_value() {
  local key="$1" file="$2"
  [[ "$key" =~ ^[A-Z][A-Z0-9_]*$ ]] || return 1
  [ -f "$file" ] || return 1
  sed -n "s/^${key}=//p" "$file" | tail -n1
}

write_deployment_state() {
  local path="$1" resource_group="$2" deployment_name="$3" location="$4"
  [[ "$resource_group" != *$'\n'* && "$deployment_name" != *$'\n'* && "$location" != *$'\n'* ]] ||
    die "Deployment state values must not contain newlines."
  umask 077
  printf '%s\n' \
    '# Generated by deploy.sh. Contains resource identifiers only.' \
    "RESOURCE_GROUP=${resource_group}" \
    "DEPLOYMENT_NAME=${deployment_name}" \
    "LOCATION=${location}" > "$path"
}
