#!/usr/bin/env bash
# ===========================================================================
# scripts/zt-postdeploy.sh — shared post-deploy ZeroTier authorization
# ---------------------------------------------------------------------------
# Sourced by each scenario's deploy.sh. After the NVAs have joined the
# network, this authorizes both members and pins deterministic overlay IPs
# via the ZeroTier Central REST API, then records them in a gitignored
# .zt-overlay.env for apply-frr.sh / verification to consume.
#
# If no API token is supplied it degrades gracefully: it prints the manual
# portal steps and exits cleanly (the lab still works, just not hands-free).
#
# Requires (on the deploy host, only when a token is used): curl, jq.
# ===========================================================================

# _zt_node_id RG VM  ->  the 10-hex ZeroTier node/member ID (or empty)
_zt_node_id() {
  local rg="$1" vm="$2" msg
  msg="$(az vm run-command invoke -g "$rg" -n "$vm" --command-id RunShellScript \
    --scripts "sudo zerotier-cli info | awk '{print \$3}'" \
    --query 'value[0].message' -o tsv 2>/dev/null || true)"
  printf '%s' "$msg" | grep -oiE '[0-9a-f]{10}' | head -n1
}

# _zt_manual_hint NETWORK_ID  ->  print the fallback manual instructions
_zt_manual_hint() {
  local netid="$1"
  cat <<EOF

[manual step] Automatic authorization was skipped.
  1. Open https://my.zerotier.com/network/${netid}
  2. Authorize hub-nva and onprem-nva (tick the "Auth?" box).
  3. Assign overlay IPs — recommended: hub-nva 172.27.0.10, onprem-nva 172.27.0.20.
  4. Scenario 2: pass those IPs to ./apply-frr.sh when prompted.
EOF
}

# zt_postdeploy RG ZT_NETID OUT_ENV [HUB_IP] [ONPREM_IP]
# Authorizes both NVAs, pins their overlay IPs, and writes OUT_ENV.
zt_postdeploy() {
  local rg="$1" netid="$2" out_env="$3"
  local hub_ip="${4:-172.27.0.10}" onprem_ip="${5:-172.27.0.20}"
  local here; here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=/dev/null
  source "${here}/zt-api.sh"

  local token="${ZEROTIER_API_TOKEN:-}"
  if [ -z "$token" ]; then
    printf '\n'
    read -rsp "ZeroTier API token (press Enter to skip and authorize manually): " token; echo
  fi
  if [ -z "$token" ]; then
    _zt_manual_hint "$netid"
    return 0
  fi
  export ZEROTIER_API_TOKEN="$token"

  if ! zt_require; then
    echo "[warn] curl/jq not available on this host; falling back to manual authorization." >&2
    _zt_manual_hint "$netid"
    return 0
  fi

  # Deterministic overlay IPs (overridable). Must sit inside the network's managed route.
  local _h _o
  read -rp "hub-nva overlay IP [${hub_ip}]: "    _h; hub_ip="${_h:-$hub_ip}"
  read -rp "onprem-nva overlay IP [${onprem_ip}]: " _o; onprem_ip="${_o:-$onprem_ip}"

  echo "[info] Resolving ZeroTier node IDs from the NVAs..."
  local hub_node onprem_node
  hub_node="$(_zt_node_id "$rg" hub-nva)"
  onprem_node="$(_zt_node_id "$rg" onprem-nva)"
  if [ -z "$hub_node" ] || [ -z "$onprem_node" ]; then
    echo "[warn] Could not read both node IDs yet (NVAs may still be joining)." >&2
    _zt_manual_hint "$netid"
    return 0
  fi

  echo "[info] Authorizing hub-nva (${hub_node}) -> ${hub_ip}"
  if ! zt_authorize_member "$netid" "$hub_node" "hub-nva" "$hub_ip"; then
    _zt_manual_hint "$netid"; return 0
  fi
  echo "[info] Authorizing onprem-nva (${onprem_node}) -> ${onprem_ip}"
  if ! zt_authorize_member "$netid" "$onprem_node" "onprem-nva" "$onprem_ip"; then
    _zt_manual_hint "$netid"; return 0
  fi

  # Confirm the controller applied the assignment; capture whatever it returns.
  local hub_actual onprem_actual
  hub_actual="$(zt_wait_member_online "$netid" "$hub_node" 90 || true)"
  onprem_actual="$(zt_wait_member_online "$netid" "$onprem_node" 90 || true)"
  hub_ip="${hub_actual:-$hub_ip}"
  onprem_ip="${onprem_actual:-$onprem_ip}"

  cat > "$out_env" <<EOF
# Generated by deploy.sh — ZeroTier overlay IPs (no secrets; safe to delete).
HUB_OVERLAY_IP=${hub_ip}
ONPREM_OVERLAY_IP=${onprem_ip}
EOF

  echo "[ ok ] Members authorized. Overlay IPs saved to ${out_env}"
  echo "       hub-nva=${hub_ip}  onprem-nva=${onprem_ip}"
}
